name: Create File with Variables

on:
  push:
    branches:
      - main  # Change this to your main branch name if necessary

jobs:
  create_file_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set variables and create txt file
        run: |
          echo "VAR1=value1" > variables.txt
          echo "VAR2=value2" >> variables.txt
          # Add more variables as needed

      - name: Show the content of variables.txt
        run: cat variables.txt

      - name: Create branch and push changes
        run: |
          git config --local user.email "raj.vaya2017@gmail.com"
          git config --local user.name "rajvaya13"
          git checkout -b update-variables
          git add variables.txt
          git commit -m "Add variables.txt"
          git push origin update-variables
