name: Create File with Variables

on:
  push:
    branches:
      - main
      # Change this to your main branch name if necessary

jobs:
  create_file_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set variables and create txt file
        run: |
          echo "VAR1=value1" > variables.txt
          echo "VAR2=value2" >> variables.txt
          # Add more variables as needed

      - name: Show the content of variables.txt
        run: cat variables.txt

      - name: Upload txt file
        uses: actions/upload-artifact@v2
        with:
          name: variables-file
          path: ./my_temp_branch/variables.txt
