name: Send Email

on:
  push:
    branches:
      - main
      # Change this to the branch where you want the workflow to trigger (e.g., 'master' if that's your default branch)

jobs:
  send_email:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
      - name: Send an email using SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587  # Replace with the appropriate SMTP port
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: lola.berserker99@gmail.com
          to: raj.vaya2017@gmail.com
          subject: Your subject here
          body: |
            Hi there,
            
            This is the content of the email.
            
            Best regards,
            Your Name
