name: Update Variable

on:
  push:
    branches:
      - main  # Change this to your default branch name if it's not 'main'

jobs:
  update_variable:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Update variable.txt
        run: |
          # Retrieve the values of the input variables
          VAR1="${{ github.event.inputs.INPUT_VAR1 }}"
          VAR2="${{ github.event.inputs.INPUT_VAR2 }}"
          # Add more variables if needed

          # Update the content of variable.txt
          echo "VAR1=${VAR1}" > variable.txt
          echo "VAR2=${VAR2}" >> variable.txt
          # Add more lines if you have additional variables to save
          
          # Commit and push the changes back to the repository
          git config user.name "rajvaya13"
          git config user.email "raj.vaya2017@gmail.com"
          git add variable.txt
          git commit -m "Update variable.txt with workflow inputs"
          git push origin "${{ github.ref }}" --token ${{ secrets.PERSONAL_ACCESS_TOKEN }}
