name: Update Variable File
on:
  push:
    branches:
      - main # Change this to the branch you want the workflow to trigger on

jobs:
  update_variable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Variable File
      run: |
        # Replace `YOUR_VALUE_1` and `YOUR_VALUE_2` with the desired values.
        echo "variable1=YOUR_VALUE_1" > variable.txt
        echo "variable2=YOUR_VALUE_2" >> variable.txt

    - name: Commit changes
      run: |
        git config user.name "rajvaya13"
        git config user.email "raj.vaya2017@gmail.com"
        git commit -m "Update variable.txt with workflow variables" variable.txt
        git push origin main # Change "main" to the branch you want to push the changes to
