name: Update Variable File
on:
  push:
    branches:
      - main # Change this to the branch you want the workflow to trigger ons

jobs:
  update_variable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Variable File
      run: |
        # Replace `YOUR_VALUE_1` and `YOUR_VALUE_2` with the desired values.
        echo "variable1=YOUR_VALUE_1" > variable.txt
        echo "variable2=YOUR_VALUE_2" >> variable.txt
        
    - name: upload the file 
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        /usr/bin/git config --local gc.auto 0
        /usr/bin/git config --local http.https://github.com/.extraheader
        pwd
        ls -la ./scan_results/
        mv ./scan_results ./var1-101
        git fetch
        git branch
        git show-ref
        git add -f ./var1-101
        git commit -m "the changes are pushed @raj.vaya2017@gmail.com"
        git push -u origin main
