name: The sub Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed
    
jobs:
  use_variable:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: shared-data
          path: shared-data

      - name: Read variable value
        run: |
          VARIABLE_VALUE=$(cat shared-data/variable.txt)
          echo "Variable value from main workflow: $VARIABLE_VALUE"
