name: The sub Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed
    
jobs:
  use_variable:
    runs-on: ubuntu-latest

    steps:
      - name: Download asset
        uses: actions/download-artifact@v2
        with:
          name: variable
          path: variable.txt

      - name: Read variable value
        run: |
          VARIABLE_VALUE=$(cat variable.txt)
          echo "Variable value from main workflow: $VARIABLE_VALUE"
