name: The sub Workflow

#on:
 # workflow_run:
  #  workflows: ["Main Workflow"]
   # types:
    #  - completed
    
on:
  push:
    branches:
      - main

jobs:
  jobtwo:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        uses: actions/checkout@v2
 
      - name: Step 2
        run: echo "This is step 2."  
        
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Load variable from artifact
        id: load_variable
        run: |
          echo ::set-output name=my_variable::$(cat my_variable.env)

      - name: Use the variable
        run: |
          echo "My variable value is ${{ steps.load_variable.outputs.my_variable }}"        
