name: The sub Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  jobtwo:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        uses: actions/checkout@v2
 
      - name: Step 2
        run: echo "This is step 2."  
        #adc
